.TH sokochez 6 "10 July 2017" "version 0.6.2"
.SH NAME
sokochez - a local two players puzzle game inspired by sokoban
.SH SYNOPSIS
.B sokochez [-h] | [-e] 
.I file ...
.SH DESCRIPTION
.B sokochez
is a puzzle game meant to be played by two players.
There are three types of maps, their rules are :
put the blocks next to their respective positions,
put the block A next to the block B,
meet the other player.
.PP 
In order to move, use 
.B wasd
and 
.B okl;
keys. 
To open the menu, press
.BR v

.SH OPTIONS
.IP -e
open the map editor
.IP -h
display help

.SH AUTHOR
Baptiste Pouget <baba@firemail.cc>
